.github/workflows/test.yml, compose-cd, test/get_remote.sh
=> こわれたためなおした

compose-cd
- add UPDATE_REPO_ONLY
- add UPDATE_IMAGE_BY_REPO (Fix #13 )
- local image null check (Fix #12 )
=> UPDATE_REPO_ONLY, UPDATE_IMAGE_BY_REPO

compose-cd, test/get_remote.sh
=> privateなイメージのmanifestを取得できるようにする

compose-cd, compose-cd-cleanup.service, compose-cd-cleanup.timer, compose-cd.timer, test/get_remote.sh
- #20 
- #21 
- Fix #15 
- Fix #18 
- Fix #17
=> Release 0.3.0

compose-cd
=> Fix update_repo diff revision

compose-cd
=> shellcheckのエラーが出ても仕方ないところを黙らせる

.github/workflows/shellcheck.yml
=> Improve shellcheck CI

.github/workflows/shfmt.yml, compose-cd, test/get_remote.sh
=> shfmt suggest

.github/workflows/release.yml, compose-cd, set_version.sh
=> Release automation

.github/workflows/shellcheck.yml
=> Fix shellcheck on push(github-check)

compose-cd
=> `compose-cd install` がconfigに設定する値をオプションで渡せるようにする

.github/workflows/shellcheck.yml, compose-cd
=> Fix shellcheck ２(ツー)

.gitattributes, .github/workflows/release.yml, compose-cd
=> Release archive files

.github/workflows/release.yml, compose-cd
=> Release checksums

compose-cd
=> [breaking change] .compose-apply use relative path from .compose-cd dir

compose-cd
=> Save installed version into config file

compose-cd
=> add: warning breaking change

compose-cd
=> Release 0.4

LICENSE, README.md
=> Add docs to README

compose-cd
=> Fix commit hash variables for apply

compose-cd
=> pull container image quiet

compose-cd
あと，これとは関係ないけどwildcardのexpandも直すべき
_Originally posted by @sksat in https://github.com/sksat/compose-cd/issues/61#issuecomment-1024857054_
=> Fix expand apply-list wildcard

compose-cd
Resolve #97 
- Add `NOTIFY_USERNAME` global config
- Example config(`/etc/compose-cd/config`)
```bash
NOTIFY_USERNAME="$(hostname)"
```
=> Add NOTIFY_USERNAME config

compose-cd
=> Add log wrapper

compose-cd
- Resolve #96 
- Add `REPO_GIT_REMOTE` config(optional. default value is `origin`)
=> Add git remote config

compose-cd
=> Add RESTART_WITH_BUILD option

compose-cd
=> Add RESTRICT_HOSTNAME_PATTERN

DESIGN.md
- https://hackmd.io/@sksat/rkEnvY4zq
=> Import compose-cd Design Doc from HackMD

test/get_remote.sh
- Resolve #139 
- どうにもおかしいのは kuso-subdomain-adder だけなので，テストから排除
- 別途調査はすべきだが......
=> Remove sksat/kuso-subdomain-adder:master from test for strange behavior

compose-cd
=> Change default compose implementation to docker compose V2

compose-cd
=> Fix version mismatch warning log

.github/workflows/shellcheck.yml, .github/workflows/test.yml, compose-cd
=> Fix lint & test workflow trigger
